#!/bin/bash

# Emacs
alias emacs="emacs -nw"
alias ek="e -e '(kill-emacs)'"
alias ekk="pkill -f emacs"
alias er="e -e '(kill-emacs)'; e"

# Edit bash-related files
alias sb='source ~/.profile' # reload profile
alias eb='e $DOT_DIR' # edit dotfiles
alias ec="crontab -e" # edit cronjobs
