#!/bin/bash

# Git
alias g="git status"
alias ga="git add"
alias gaa="git add --all ."
alias gac='git commit -a -m '
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -d"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gcot="git checkout -t"
alias gf="git fetch"
alias gm="git merge"
alias gmn="git merge --no-ff"
alias gr="git rebase"
alias gri="git rebase -i"
alias griu="git rebase -i @{upstream}"
alias gl="git log"
alias glg='git log --graph --oneline --all --decorate --remotes'
alias glr=" git --no-pager log --graph --abbrev-commit --date=relative -10 --all --pretty='tformat:%C(yellow)%h%Creset -%C(red)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias gs="git show"
alias gd="git diff"
alias gbl="git blame"
alias gps="git push"
alias gpsd="git push --delete"
alias gpso="git push -u origin"
alias gpsdo="git push --delete origin"
alias gpl="git pull"

# Github
eval "$(hub alias -s)"
