#!/bin/bash

# Tmux

_not_inside_tmux() {
    [[ -z "$TMUX" ]]
}

ensure_tmux_is_running() {
    if _not_inside_tmux; then
        tat # requires tat script be present in $PATH
    fi
}

ensure_tmux_is_running
