#!/bin/sh
# -*- sh -*-

# vamp stuff for Icarus converter
export PATH="$PATH:~/code/fugue/bin"
export VAMP_PATH="~/code/fugue/bin"

# db_models config
export CONFIG_PATH="$HOME/code/fugue/config"
export ENV="prod"

# Fugue path for Vagrant
export FUGUE_PATH="$HOME/code/fugue"
