#!/bin/sh
# -*- sh -*-

### RUMBLEFISH STUFFS
rfserver ()
{
  ssh -i ~/.ssh/rumblefish-ops-us-west-2.pem 'ubuntu@'$1'' $2
}

hfaserver ()
{
  ssh -i ~/.ssh/hfa-ops.pem 'ubuntu@'$1'' $2
}

hfavpn ()
{
    echo "$1" | \
    sudo openconnect \
         --user=imacdonald \
         --passwd-on-stdin \
         --authgroup=EMP-Access \
         --no-cert-check \
         vpn.sesac.com
}

hfachat()
{
    case "$1" in
        falcon)
            open "http://bit.ly/sesac_millenium_falcon"
            ;;
        death)
            open "http://bit.ly/sesac_death_star"
            ;;
        scrum)
            open "http://bit.ly/sesac_scrum"
            ;;
        mm)
            open "http://bit.ly/sesac_matchmaker"
            ;;
        front)
            open "http://bit.ly/sesac_frontend"
            ;;
        back)
            open "http://bit.ly/sesac_backend"
            ;;
        liink)
            open "http://bit.ly/sesac_liink"
            ;;
        *)
            open "http://bit.ly/sesac_millenium_falcon"
            ;;
    esac
}
