#!/bin/bash

### RUMBLEFISH STUFFS
rfserver ()
{
    # shellcheck disable=SC2029
    ssh -i ~/.ssh/rumblefish-ops-us-west-2.pem 'ubuntu@'"$1"'' "$2"
}

hfaserver ()
{
    # shellcheck disable=SC2029
    ssh -i ~/.ssh/hfa-ops.pem 'ubuntu@'"$1"'' "$2"
}

hfavpn ()
{
    host=${2:-'https://vpn.harryfox.com'}
    group=${3:-'HFAVPN'}
    user=${4:-'imacdonald'}
    echo "$1" | \
    sudo openconnect \
         --user="$user" \
         --passwd-on-stdin \
         --authgroup="$group" \
         "$host"
}

# --no-cert-check \
hfachat()
{
    case "$1" in
        falcon)
            open "http://bit.ly/sesac_millenium_falcon"
            ;;
        death)
            open "http://bit.ly/sesac_death_star"
            ;;
        scrum)
            open "http://bit.ly/sesac_scrum"
            ;;
        mm)
            open "http://bit.ly/sesac_matchmaker"
            ;;
        front)
            open "http://bit.ly/sesac_frontend"
            ;;
        back)
            open "http://bit.ly/sesac_backend"
            ;;
        liink)
            open "http://bit.ly/sesac_liink"
            ;;
        *)
            open "http://bit.ly/sesac_millenium_falcon"
            ;;
    esac
}
