#!/bin/bash

set -o emacs

# History
shopt -s histappend

# homebrew bash completion
# Add tab completion for bash completion 2
if which brew > /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
    source "$(brew --prefix)/share/bash-completion/bash_completion";
elif [[ -f /etc/bash_completion ]]; then
    source /etc/bash_completion;
fi;

#AWS CLI completion
complete -C aws_completer aws
