#!/bin/sh
# -*- sh -*-

set -o emacs

# History
shopt -s histappend

# homebrew bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# git bash completion
if [ -f etc/git-completion.bash ]; then
  source etc/git-completion.bash
fi

#AWS CLI completion
complete -C aws_completer aws

# SSH keys
for key in $(ls ~/.ssh/*[!.pub,known_hosts,youtube_publishing_key.pub]); do ssh-add $key &>/dev/null; done

# Docker
# eval "$(docker-machine env default)"
# eval $(docker-machine env hfa-aws-mongo)
# eval $(docker-machine env sesac-api-staging)

# GO
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
