#!/bin/bash

set -o emacs

# History
shopt -s histappend

# homebrew bash completion
if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    # shellcheck source=/dev/null
    . "$(brew --prefix)/etc/bash_completion"
fi

# git bash completion
if [ -f etc/git-completion.bash ]; then
    # shellcheck source=/dev/null
    source etc/git-completion.bash
fi

#AWS CLI completion
complete -C aws_completer aws

# SSH keys
for key in "$HOME/.ssh/*[!.pub,known_hosts,youtube_publishing_key.pub]"
do
    ssh-add "$key" &>/dev/null
done

# GO
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
