#!/bin/bash

# Used to have alias server='python -m SimpleHTTPServer 4567'
# start simple http server
serve() {
    port=${1:-8080}
    open "http://localhost:$port"
    ruby -run -e httpd . -p "$port"
}

# SSH keys

add-ssh-keys() {
    for key in "$HOME"/.ssh/*
    do
        [[ "$key" =~ .*(.csv|.pub|known_hosts|authorized_keys|youtube_publishing_key.pub|youtube_publishing_key|yt_publishing_key.ppk)$ ]] && continue
        ssh-add "$key" &>/dev/null
    done
}
